### ISSUE TITLE
Grab metrics from multiple bind servers

### ISSUE THREAD

**Issue by bondif** [prometheus-community/bind_exporter#103]
Hi 👋
Can we gather metrics from multiple bind servers? If not please mark this as feature-request
Thanks

**Comment by SuperQ** [comment]
Yes, the bind_exporter is designed to be deployed as a "sidecar". On each server where you run bind, you run the exporter. It monitors over localhost and Prometheus connects to the node over HTTP.

Otherwise features like the built-in bind process collector don't work.

**Comment by bondif** [comment]
That makes sense, thanks.

**Comment by phpipam** [comment]
Just as a note, you can also run multiple instances of bind-exporters, each on separate port. Seems to work fine.

```Shell
[root@prometheus:/]# ps aux | grep bind
/usr/bin/prometheus-bind-exporter --bind.stats-url=http://x.x.x.1:8053/ --web.listen-address=:9119
/usr/bin/prometheus-bind-exporter --bind.stats-url=http://x.x.x.2:8053/ --web.listen-address=:9120
/usr/bin/prometheus-bind-exporter --bind.stats-url=http://x.x.x.3:8053/ --web.listen-address=:9121
```

systemd files:
```Shell
[root@prometheus:/etc/systemd/system]# ls -l | grep bind
-rw-r--r-- 1 root root  487 Nov 25 21:17 prometheus_bind_1.service
-rw-r--r-- 1 root root  487 Nov 25 21:26 prometheus_bind_2.service
-rw-r--r-- 1 root root  487 Nov 25 21:26 prometheus_bind_3.service
```

service example:
```shell
[root@prometheus:/etc/systemd/system]# more prometheus_bind_1.service
[Unit]
Description=Prometheus bind exporter
Documentation=https://manpages.debian.org/unstable/prometheus-bind-exporter/prometheus-bind-exporter.1.en.html
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecReload=/bin/kill -HUP
ExecStart=/usr/bin/prometheus-bind-exporter --bind.stats-url=http://x.x.x.1:8053/ --web.listen-address=:9119

SyslogIdentifier=prometheus
Restart=always

[Install]
WantedBy=multi-user.target
```

prometheus.yml:
```yml
  # dns
  - job_name: 'dns1'
    static_configs:
      - targets:
          - 'localhost:9119'

  - job_name: 'dns2'
    static_configs:
      - targets:
          - 'localhost:9120'
 
  - job_name: 'dns3'
    static_configs:
      - targets:
          - 'localhost:9121'
```
